FROM golang:1.10-alpine3.8

RUN apk add --no-cache --update git

WORKDIR /go/src/github.com/LensPlatform/Services/user-service
COPY . .

RUN go get -d -v \
  && go install -v \
  && go build

EXPOSE 8085
CMD ["./src/cmd/svc"]