FROM golang:1.13

ENV SERVICE_PATH /go/src/github.com/LensPlatform/Services/user-service

WORKDIR $SERVICE_PATH
COPY . .

RUN \
    go get -d -v \
    && go install -v \
    && go build

EXPOSE 8085
CMD ["./src/cmd/svc"]