// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/pkg/grpc/pb/users.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserAccountRequest) Reset()         { *m = CreateUserAccountRequest{} }
func (m *CreateUserAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserAccountRequest) ProtoMessage()    {}
func (*CreateUserAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{0}
}

func (m *CreateUserAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserAccountRequest.Unmarshal(m, b)
}
func (m *CreateUserAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserAccountRequest.Merge(m, src)
}
func (m *CreateUserAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserAccountRequest.Size(m)
}
func (m *CreateUserAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserAccountRequest proto.InternalMessageInfo

type CreateUserAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserAccountReply) Reset()         { *m = CreateUserAccountReply{} }
func (m *CreateUserAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserAccountReply) ProtoMessage()    {}
func (*CreateUserAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{1}
}

func (m *CreateUserAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserAccountReply.Unmarshal(m, b)
}
func (m *CreateUserAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateUserAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserAccountReply.Merge(m, src)
}
func (m *CreateUserAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserAccountReply.Size(m)
}
func (m *CreateUserAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserAccountReply proto.InternalMessageInfo

type UpdateUserAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserAccountRequest) Reset()         { *m = UpdateUserAccountRequest{} }
func (m *UpdateUserAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAccountRequest) ProtoMessage()    {}
func (*UpdateUserAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{2}
}

func (m *UpdateUserAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAccountRequest.Unmarshal(m, b)
}
func (m *UpdateUserAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAccountRequest.Merge(m, src)
}
func (m *UpdateUserAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAccountRequest.Size(m)
}
func (m *UpdateUserAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAccountRequest proto.InternalMessageInfo

type UpdateUserAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserAccountReply) Reset()         { *m = UpdateUserAccountReply{} }
func (m *UpdateUserAccountReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAccountReply) ProtoMessage()    {}
func (*UpdateUserAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{3}
}

func (m *UpdateUserAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAccountReply.Unmarshal(m, b)
}
func (m *UpdateUserAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAccountReply.Marshal(b, m, deterministic)
}
func (m *UpdateUserAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAccountReply.Merge(m, src)
}
func (m *UpdateUserAccountReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAccountReply.Size(m)
}
func (m *UpdateUserAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAccountReply proto.InternalMessageInfo

type DeleteUserAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserAccountRequest) Reset()         { *m = DeleteUserAccountRequest{} }
func (m *DeleteUserAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserAccountRequest) ProtoMessage()    {}
func (*DeleteUserAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{4}
}

func (m *DeleteUserAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserAccountRequest.Unmarshal(m, b)
}
func (m *DeleteUserAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserAccountRequest.Merge(m, src)
}
func (m *DeleteUserAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserAccountRequest.Size(m)
}
func (m *DeleteUserAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserAccountRequest proto.InternalMessageInfo

type DeleteUserAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserAccountReply) Reset()         { *m = DeleteUserAccountReply{} }
func (m *DeleteUserAccountReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserAccountReply) ProtoMessage()    {}
func (*DeleteUserAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{5}
}

func (m *DeleteUserAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserAccountReply.Unmarshal(m, b)
}
func (m *DeleteUserAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserAccountReply.Marshal(b, m, deterministic)
}
func (m *DeleteUserAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserAccountReply.Merge(m, src)
}
func (m *DeleteUserAccountReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserAccountReply.Size(m)
}
func (m *DeleteUserAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserAccountReply proto.InternalMessageInfo

type GetUserAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAccountRequest) Reset()         { *m = GetUserAccountRequest{} }
func (m *GetUserAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserAccountRequest) ProtoMessage()    {}
func (*GetUserAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{6}
}

func (m *GetUserAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAccountRequest.Unmarshal(m, b)
}
func (m *GetUserAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetUserAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAccountRequest.Merge(m, src)
}
func (m *GetUserAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserAccountRequest.Size(m)
}
func (m *GetUserAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAccountRequest proto.InternalMessageInfo

type GetUserAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAccountReply) Reset()         { *m = GetUserAccountReply{} }
func (m *GetUserAccountReply) String() string { return proto.CompactTextString(m) }
func (*GetUserAccountReply) ProtoMessage()    {}
func (*GetUserAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{7}
}

func (m *GetUserAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAccountReply.Unmarshal(m, b)
}
func (m *GetUserAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAccountReply.Marshal(b, m, deterministic)
}
func (m *GetUserAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAccountReply.Merge(m, src)
}
func (m *GetUserAccountReply) XXX_Size() int {
	return xxx_messageInfo_GetUserAccountReply.Size(m)
}
func (m *GetUserAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAccountReply proto.InternalMessageInfo

type CreateTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTeamsAccountRequest) Reset()         { *m = CreateTeamsAccountRequest{} }
func (m *CreateTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTeamsAccountRequest) ProtoMessage()    {}
func (*CreateTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{8}
}

func (m *CreateTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamsAccountRequest.Unmarshal(m, b)
}
func (m *CreateTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamsAccountRequest.Merge(m, src)
}
func (m *CreateTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTeamsAccountRequest.Size(m)
}
func (m *CreateTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamsAccountRequest proto.InternalMessageInfo

type CreateTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTeamsAccountReply) Reset()         { *m = CreateTeamsAccountReply{} }
func (m *CreateTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateTeamsAccountReply) ProtoMessage()    {}
func (*CreateTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{9}
}

func (m *CreateTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTeamsAccountReply.Unmarshal(m, b)
}
func (m *CreateTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTeamsAccountReply.Merge(m, src)
}
func (m *CreateTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateTeamsAccountReply.Size(m)
}
func (m *CreateTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTeamsAccountReply proto.InternalMessageInfo

type UpdateTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamsAccountRequest) Reset()         { *m = UpdateTeamsAccountRequest{} }
func (m *UpdateTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamsAccountRequest) ProtoMessage()    {}
func (*UpdateTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{10}
}

func (m *UpdateTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamsAccountRequest.Unmarshal(m, b)
}
func (m *UpdateTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamsAccountRequest.Merge(m, src)
}
func (m *UpdateTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamsAccountRequest.Size(m)
}
func (m *UpdateTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamsAccountRequest proto.InternalMessageInfo

type UpdateTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTeamsAccountReply) Reset()         { *m = UpdateTeamsAccountReply{} }
func (m *UpdateTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamsAccountReply) ProtoMessage()    {}
func (*UpdateTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{11}
}

func (m *UpdateTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamsAccountReply.Unmarshal(m, b)
}
func (m *UpdateTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *UpdateTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamsAccountReply.Merge(m, src)
}
func (m *UpdateTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamsAccountReply.Size(m)
}
func (m *UpdateTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamsAccountReply proto.InternalMessageInfo

type DeleteTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeamsAccountRequest) Reset()         { *m = DeleteTeamsAccountRequest{} }
func (m *DeleteTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamsAccountRequest) ProtoMessage()    {}
func (*DeleteTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{12}
}

func (m *DeleteTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamsAccountRequest.Unmarshal(m, b)
}
func (m *DeleteTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamsAccountRequest.Merge(m, src)
}
func (m *DeleteTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamsAccountRequest.Size(m)
}
func (m *DeleteTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamsAccountRequest proto.InternalMessageInfo

type DeleteTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTeamsAccountReply) Reset()         { *m = DeleteTeamsAccountReply{} }
func (m *DeleteTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*DeleteTeamsAccountReply) ProtoMessage()    {}
func (*DeleteTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{13}
}

func (m *DeleteTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTeamsAccountReply.Unmarshal(m, b)
}
func (m *DeleteTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *DeleteTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTeamsAccountReply.Merge(m, src)
}
func (m *DeleteTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_DeleteTeamsAccountReply.Size(m)
}
func (m *DeleteTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTeamsAccountReply proto.InternalMessageInfo

type GetTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamsAccountRequest) Reset()         { *m = GetTeamsAccountRequest{} }
func (m *GetTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetTeamsAccountRequest) ProtoMessage()    {}
func (*GetTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{14}
}

func (m *GetTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsAccountRequest.Unmarshal(m, b)
}
func (m *GetTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsAccountRequest.Merge(m, src)
}
func (m *GetTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetTeamsAccountRequest.Size(m)
}
func (m *GetTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsAccountRequest proto.InternalMessageInfo

type GetTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamsAccountReply) Reset()         { *m = GetTeamsAccountReply{} }
func (m *GetTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*GetTeamsAccountReply) ProtoMessage()    {}
func (*GetTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{15}
}

func (m *GetTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsAccountReply.Unmarshal(m, b)
}
func (m *GetTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *GetTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsAccountReply.Merge(m, src)
}
func (m *GetTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_GetTeamsAccountReply.Size(m)
}
func (m *GetTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsAccountReply proto.InternalMessageInfo

type AddUserToTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserToTeamsAccountRequest) Reset()         { *m = AddUserToTeamsAccountRequest{} }
func (m *AddUserToTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserToTeamsAccountRequest) ProtoMessage()    {}
func (*AddUserToTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{16}
}

func (m *AddUserToTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserToTeamsAccountRequest.Unmarshal(m, b)
}
func (m *AddUserToTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserToTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *AddUserToTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserToTeamsAccountRequest.Merge(m, src)
}
func (m *AddUserToTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserToTeamsAccountRequest.Size(m)
}
func (m *AddUserToTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserToTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserToTeamsAccountRequest proto.InternalMessageInfo

type AddUserToTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserToTeamsAccountReply) Reset()         { *m = AddUserToTeamsAccountReply{} }
func (m *AddUserToTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*AddUserToTeamsAccountReply) ProtoMessage()    {}
func (*AddUserToTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{17}
}

func (m *AddUserToTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserToTeamsAccountReply.Unmarshal(m, b)
}
func (m *AddUserToTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserToTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *AddUserToTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserToTeamsAccountReply.Merge(m, src)
}
func (m *AddUserToTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_AddUserToTeamsAccountReply.Size(m)
}
func (m *AddUserToTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserToTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserToTeamsAccountReply proto.InternalMessageInfo

type DeleteUserFromTeamsAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserFromTeamsAccountRequest) Reset()         { *m = DeleteUserFromTeamsAccountRequest{} }
func (m *DeleteUserFromTeamsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserFromTeamsAccountRequest) ProtoMessage()    {}
func (*DeleteUserFromTeamsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{18}
}

func (m *DeleteUserFromTeamsAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserFromTeamsAccountRequest.Unmarshal(m, b)
}
func (m *DeleteUserFromTeamsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserFromTeamsAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserFromTeamsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserFromTeamsAccountRequest.Merge(m, src)
}
func (m *DeleteUserFromTeamsAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserFromTeamsAccountRequest.Size(m)
}
func (m *DeleteUserFromTeamsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserFromTeamsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserFromTeamsAccountRequest proto.InternalMessageInfo

type DeleteUserFromTeamsAccountReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserFromTeamsAccountReply) Reset()         { *m = DeleteUserFromTeamsAccountReply{} }
func (m *DeleteUserFromTeamsAccountReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserFromTeamsAccountReply) ProtoMessage()    {}
func (*DeleteUserFromTeamsAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{19}
}

func (m *DeleteUserFromTeamsAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserFromTeamsAccountReply.Unmarshal(m, b)
}
func (m *DeleteUserFromTeamsAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserFromTeamsAccountReply.Marshal(b, m, deterministic)
}
func (m *DeleteUserFromTeamsAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserFromTeamsAccountReply.Merge(m, src)
}
func (m *DeleteUserFromTeamsAccountReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserFromTeamsAccountReply.Size(m)
}
func (m *DeleteUserFromTeamsAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserFromTeamsAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserFromTeamsAccountReply proto.InternalMessageInfo

type CreateGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{20}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

type CreateGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReply) Reset()         { *m = CreateGroupReply{} }
func (m *CreateGroupReply) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReply) ProtoMessage()    {}
func (*CreateGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{21}
}

func (m *CreateGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReply.Unmarshal(m, b)
}
func (m *CreateGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReply.Marshal(b, m, deterministic)
}
func (m *CreateGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReply.Merge(m, src)
}
func (m *CreateGroupReply) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReply.Size(m)
}
func (m *CreateGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReply proto.InternalMessageInfo

type SubscribeToGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToGroupRequest) Reset()         { *m = SubscribeToGroupRequest{} }
func (m *SubscribeToGroupRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToGroupRequest) ProtoMessage()    {}
func (*SubscribeToGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{22}
}

func (m *SubscribeToGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToGroupRequest.Unmarshal(m, b)
}
func (m *SubscribeToGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToGroupRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeToGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToGroupRequest.Merge(m, src)
}
func (m *SubscribeToGroupRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToGroupRequest.Size(m)
}
func (m *SubscribeToGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToGroupRequest proto.InternalMessageInfo

type SubscribeToGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToGroupReply) Reset()         { *m = SubscribeToGroupReply{} }
func (m *SubscribeToGroupReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeToGroupReply) ProtoMessage()    {}
func (*SubscribeToGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{23}
}

func (m *SubscribeToGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToGroupReply.Unmarshal(m, b)
}
func (m *SubscribeToGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToGroupReply.Marshal(b, m, deterministic)
}
func (m *SubscribeToGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToGroupReply.Merge(m, src)
}
func (m *SubscribeToGroupReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeToGroupReply.Size(m)
}
func (m *SubscribeToGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToGroupReply proto.InternalMessageInfo

type UnsubscribeFromGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeFromGroupRequest) Reset()         { *m = UnsubscribeFromGroupRequest{} }
func (m *UnsubscribeFromGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeFromGroupRequest) ProtoMessage()    {}
func (*UnsubscribeFromGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{24}
}

func (m *UnsubscribeFromGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeFromGroupRequest.Unmarshal(m, b)
}
func (m *UnsubscribeFromGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeFromGroupRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeFromGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeFromGroupRequest.Merge(m, src)
}
func (m *UnsubscribeFromGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeFromGroupRequest.Size(m)
}
func (m *UnsubscribeFromGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeFromGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeFromGroupRequest proto.InternalMessageInfo

type UnsubscribeFromGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeFromGroupReply) Reset()         { *m = UnsubscribeFromGroupReply{} }
func (m *UnsubscribeFromGroupReply) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeFromGroupReply) ProtoMessage()    {}
func (*UnsubscribeFromGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{25}
}

func (m *UnsubscribeFromGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeFromGroupReply.Unmarshal(m, b)
}
func (m *UnsubscribeFromGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeFromGroupReply.Marshal(b, m, deterministic)
}
func (m *UnsubscribeFromGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeFromGroupReply.Merge(m, src)
}
func (m *UnsubscribeFromGroupReply) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeFromGroupReply.Size(m)
}
func (m *UnsubscribeFromGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeFromGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeFromGroupReply proto.InternalMessageInfo

type DeleteGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{26}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

type DeleteGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupReply) Reset()         { *m = DeleteGroupReply{} }
func (m *DeleteGroupReply) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupReply) ProtoMessage()    {}
func (*DeleteGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{27}
}

func (m *DeleteGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupReply.Unmarshal(m, b)
}
func (m *DeleteGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupReply.Marshal(b, m, deterministic)
}
func (m *DeleteGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupReply.Merge(m, src)
}
func (m *DeleteGroupReply) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupReply.Size(m)
}
func (m *DeleteGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupReply proto.InternalMessageInfo

type UpdateGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{28}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

type UpdateGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupReply) Reset()         { *m = UpdateGroupReply{} }
func (m *UpdateGroupReply) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupReply) ProtoMessage()    {}
func (*UpdateGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{29}
}

func (m *UpdateGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupReply.Unmarshal(m, b)
}
func (m *UpdateGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupReply.Marshal(b, m, deterministic)
}
func (m *UpdateGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupReply.Merge(m, src)
}
func (m *UpdateGroupReply) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupReply.Size(m)
}
func (m *UpdateGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupReply proto.InternalMessageInfo

type GetGroupByIDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByIDRequest) Reset()         { *m = GetGroupByIDRequest{} }
func (m *GetGroupByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupByIDRequest) ProtoMessage()    {}
func (*GetGroupByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{30}
}

func (m *GetGroupByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByIDRequest.Unmarshal(m, b)
}
func (m *GetGroupByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByIDRequest.Merge(m, src)
}
func (m *GetGroupByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupByIDRequest.Size(m)
}
func (m *GetGroupByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByIDRequest proto.InternalMessageInfo

type GetGroupByIDReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByIDReply) Reset()         { *m = GetGroupByIDReply{} }
func (m *GetGroupByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupByIDReply) ProtoMessage()    {}
func (*GetGroupByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{31}
}

func (m *GetGroupByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByIDReply.Unmarshal(m, b)
}
func (m *GetGroupByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByIDReply.Marshal(b, m, deterministic)
}
func (m *GetGroupByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByIDReply.Merge(m, src)
}
func (m *GetGroupByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupByIDReply.Size(m)
}
func (m *GetGroupByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByIDReply proto.InternalMessageInfo

type GetGroupByNameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByNameRequest) Reset()         { *m = GetGroupByNameRequest{} }
func (m *GetGroupByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupByNameRequest) ProtoMessage()    {}
func (*GetGroupByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{32}
}

func (m *GetGroupByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByNameRequest.Unmarshal(m, b)
}
func (m *GetGroupByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByNameRequest.Merge(m, src)
}
func (m *GetGroupByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupByNameRequest.Size(m)
}
func (m *GetGroupByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByNameRequest proto.InternalMessageInfo

type GetGroupByNameReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByNameReply) Reset()         { *m = GetGroupByNameReply{} }
func (m *GetGroupByNameReply) String() string { return proto.CompactTextString(m) }
func (*GetGroupByNameReply) ProtoMessage()    {}
func (*GetGroupByNameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{33}
}

func (m *GetGroupByNameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByNameReply.Unmarshal(m, b)
}
func (m *GetGroupByNameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByNameReply.Marshal(b, m, deterministic)
}
func (m *GetGroupByNameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByNameReply.Merge(m, src)
}
func (m *GetGroupByNameReply) XXX_Size() int {
	return xxx_messageInfo_GetGroupByNameReply.Size(m)
}
func (m *GetGroupByNameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByNameReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByNameReply proto.InternalMessageInfo

type IsGroupPrivateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsGroupPrivateRequest) Reset()         { *m = IsGroupPrivateRequest{} }
func (m *IsGroupPrivateRequest) String() string { return proto.CompactTextString(m) }
func (*IsGroupPrivateRequest) ProtoMessage()    {}
func (*IsGroupPrivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{34}
}

func (m *IsGroupPrivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsGroupPrivateRequest.Unmarshal(m, b)
}
func (m *IsGroupPrivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsGroupPrivateRequest.Marshal(b, m, deterministic)
}
func (m *IsGroupPrivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsGroupPrivateRequest.Merge(m, src)
}
func (m *IsGroupPrivateRequest) XXX_Size() int {
	return xxx_messageInfo_IsGroupPrivateRequest.Size(m)
}
func (m *IsGroupPrivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsGroupPrivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsGroupPrivateRequest proto.InternalMessageInfo

type IsGroupPrivateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsGroupPrivateReply) Reset()         { *m = IsGroupPrivateReply{} }
func (m *IsGroupPrivateReply) String() string { return proto.CompactTextString(m) }
func (*IsGroupPrivateReply) ProtoMessage()    {}
func (*IsGroupPrivateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49085d531415364, []int{35}
}

func (m *IsGroupPrivateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsGroupPrivateReply.Unmarshal(m, b)
}
func (m *IsGroupPrivateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsGroupPrivateReply.Marshal(b, m, deterministic)
}
func (m *IsGroupPrivateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsGroupPrivateReply.Merge(m, src)
}
func (m *IsGroupPrivateReply) XXX_Size() int {
	return xxx_messageInfo_IsGroupPrivateReply.Size(m)
}
func (m *IsGroupPrivateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IsGroupPrivateReply.DiscardUnknown(m)
}

var xxx_messageInfo_IsGroupPrivateReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateUserAccountRequest)(nil), "pb.CreateUserAccountRequest")
	proto.RegisterType((*CreateUserAccountReply)(nil), "pb.CreateUserAccountReply")
	proto.RegisterType((*UpdateUserAccountRequest)(nil), "pb.UpdateUserAccountRequest")
	proto.RegisterType((*UpdateUserAccountReply)(nil), "pb.UpdateUserAccountReply")
	proto.RegisterType((*DeleteUserAccountRequest)(nil), "pb.DeleteUserAccountRequest")
	proto.RegisterType((*DeleteUserAccountReply)(nil), "pb.DeleteUserAccountReply")
	proto.RegisterType((*GetUserAccountRequest)(nil), "pb.GetUserAccountRequest")
	proto.RegisterType((*GetUserAccountReply)(nil), "pb.GetUserAccountReply")
	proto.RegisterType((*CreateTeamsAccountRequest)(nil), "pb.CreateTeamsAccountRequest")
	proto.RegisterType((*CreateTeamsAccountReply)(nil), "pb.CreateTeamsAccountReply")
	proto.RegisterType((*UpdateTeamsAccountRequest)(nil), "pb.UpdateTeamsAccountRequest")
	proto.RegisterType((*UpdateTeamsAccountReply)(nil), "pb.UpdateTeamsAccountReply")
	proto.RegisterType((*DeleteTeamsAccountRequest)(nil), "pb.DeleteTeamsAccountRequest")
	proto.RegisterType((*DeleteTeamsAccountReply)(nil), "pb.DeleteTeamsAccountReply")
	proto.RegisterType((*GetTeamsAccountRequest)(nil), "pb.GetTeamsAccountRequest")
	proto.RegisterType((*GetTeamsAccountReply)(nil), "pb.GetTeamsAccountReply")
	proto.RegisterType((*AddUserToTeamsAccountRequest)(nil), "pb.AddUserToTeamsAccountRequest")
	proto.RegisterType((*AddUserToTeamsAccountReply)(nil), "pb.AddUserToTeamsAccountReply")
	proto.RegisterType((*DeleteUserFromTeamsAccountRequest)(nil), "pb.DeleteUserFromTeamsAccountRequest")
	proto.RegisterType((*DeleteUserFromTeamsAccountReply)(nil), "pb.DeleteUserFromTeamsAccountReply")
	proto.RegisterType((*CreateGroupRequest)(nil), "pb.CreateGroupRequest")
	proto.RegisterType((*CreateGroupReply)(nil), "pb.CreateGroupReply")
	proto.RegisterType((*SubscribeToGroupRequest)(nil), "pb.SubscribeToGroupRequest")
	proto.RegisterType((*SubscribeToGroupReply)(nil), "pb.SubscribeToGroupReply")
	proto.RegisterType((*UnsubscribeFromGroupRequest)(nil), "pb.UnsubscribeFromGroupRequest")
	proto.RegisterType((*UnsubscribeFromGroupReply)(nil), "pb.UnsubscribeFromGroupReply")
	proto.RegisterType((*DeleteGroupRequest)(nil), "pb.DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupReply)(nil), "pb.DeleteGroupReply")
	proto.RegisterType((*UpdateGroupRequest)(nil), "pb.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupReply)(nil), "pb.UpdateGroupReply")
	proto.RegisterType((*GetGroupByIDRequest)(nil), "pb.GetGroupByIDRequest")
	proto.RegisterType((*GetGroupByIDReply)(nil), "pb.GetGroupByIDReply")
	proto.RegisterType((*GetGroupByNameRequest)(nil), "pb.GetGroupByNameRequest")
	proto.RegisterType((*GetGroupByNameReply)(nil), "pb.GetGroupByNameReply")
	proto.RegisterType((*IsGroupPrivateRequest)(nil), "pb.IsGroupPrivateRequest")
	proto.RegisterType((*IsGroupPrivateReply)(nil), "pb.IsGroupPrivateReply")
}

func init() { proto.RegisterFile("users/pkg/grpc/pb/users.proto", fileDescriptor_a49085d531415364) }

var fileDescriptor_a49085d531415364 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x96, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0x41, 0xd0, 0x87, 0x51, 0xb4, 0xdd, 0xe6, 0x72, 0xb9, 0x4d, 0xd2, 0xda, 0x16, 0x5f,
	0x13, 0xd0, 0x47, 0x41, 0xa8, 0x06, 0x43, 0x05, 0xa5, 0x68, 0x22, 0xf8, 0x98, 0x4b, 0x96, 0x5a,
	0x4c, 0x7a, 0xeb, 0xfd, 0x10, 0xf2, 0x07, 0xfb, 0x7f, 0xc8, 0xdc, 0xec, 0x79, 0xb7, 0xbb, 0xb3,
	0xe9, 0xeb, 0x7c, 0xe7, 0xfb, 0xcd, 0xde, 0xee, 0xcc, 0x87, 0xc0, 0xb8, 0x2a, 0x54, 0x5e, 0x4c,
	0xf5, 0xaf, 0xdb, 0xe9, 0x6d, 0xae, 0xd7, 0x53, 0x9d, 0x4e, 0xeb, 0xca, 0x44, 0xe7, 0x59, 0x99,
	0x89, 0x47, 0x3a, 0xbd, 0x90, 0x30, 0xf8, 0x90, 0xab, 0x55, 0xa9, 0x96, 0x85, 0xca, 0xaf, 0xd6,
	0xeb, 0xac, 0xba, 0x2f, 0xbf, 0xaa, 0xdf, 0x95, 0x2a, 0xca, 0x8b, 0x01, 0xf4, 0x19, 0x4d, 0x6f,
	0xf7, 0xe8, 0x5a, 0xea, 0x4d, 0xd0, 0xc5, 0x68, 0xc6, 0x35, 0x53, 0x5b, 0x15, 0x72, 0x31, 0x1a,
	0xba, 0x62, 0x88, 0xe6, 0xaa, 0x64, 0x2c, 0x11, 0x9c, 0xb8, 0x02, 0xf6, 0x0f, 0x21, 0xa1, 0x53,
	0x2f, 0xd4, 0x6a, 0x57, 0x38, 0x9e, 0x04, 0x62, 0x4e, 0x34, 0x3e, 0x3a, 0x77, 0xc0, 0xc7, 0x89,
	0xc6, 0x47, 0x27, 0x0f, 0xf8, 0x38, 0x11, 0x7d, 0x03, 0xe8, 0xcf, 0x55, 0xc9, 0x99, 0xfa, 0xd0,
	0xf3, 0x14, 0x74, 0x9c, 0xc2, 0xe8, 0x6a, 0xb3, 0xc1, 0x0f, 0x5e, 0x64, 0x9c, 0x6f, 0x04, 0x32,
	0xa0, 0xa3, 0xfb, 0x12, 0xce, 0xdb, 0x1b, 0xfe, 0x98, 0x67, 0x3b, 0x2e, 0xe2, 0x1c, 0xce, 0x0e,
	0x35, 0x61, 0x4e, 0x0f, 0x04, 0x5d, 0xe1, 0x3c, 0xcf, 0x2a, 0xdd, 0x18, 0x05, 0x1c, 0x59, 0x55,
	0xec, 0x4c, 0x20, 0xfe, 0x56, 0xa5, 0xc5, 0x3a, 0xbf, 0x4b, 0xd5, 0x22, 0xb3, 0xda, 0x63, 0x88,
	0x7c, 0x09, 0x3d, 0x63, 0x18, 0x2e, 0xef, 0x8b, 0x46, 0xc2, 0x13, 0x58, 0x3e, 0x7c, 0x24, 0x56,
	0x36, 0x27, 0xa3, 0xc3, 0xbb, 0x27, 0xb3, 0xaa, 0xa6, 0x93, 0x9e, 0xd3, 0xed, 0xb4, 0xaa, 0xd8,
	0x49, 0x43, 0x56, 0x17, 0xde, 0xef, 0xaf, 0x67, 0x4d, 0xeb, 0x09, 0x1c, 0xdb, 0xe5, 0x76, 0x52,
	0x4d, 0xf1, 0xcb, 0x6a, 0xa7, 0xec, 0x49, 0xb5, 0x04, 0xd3, 0x7f, 0x5d, 0xd4, 0xd5, 0x9b, 0xfc,
	0xee, 0xcf, 0xaa, 0xec, 0xf6, 0xbb, 0x82, 0xde, 0xee, 0x5f, 0xff, 0x05, 0x78, 0x8c, 0xef, 0x52,
	0x88, 0xcf, 0x70, 0xec, 0x6d, 0xa6, 0x18, 0x4d, 0x74, 0x3a, 0x09, 0x2d, 0xb3, 0x94, 0x01, 0x55,
	0x6f, 0xf7, 0x18, 0xe7, 0xad, 0x2c, 0xc5, 0x85, 0xb6, 0x9c, 0xe2, 0xf8, 0x3d, 0xc7, 0x38, 0x6f,
	0x97, 0x29, 0x2e, 0xb4, 0xfe, 0x14, 0xc7, 0x03, 0x40, 0xcc, 0xe0, 0xb9, 0xbd, 0xe7, 0x22, 0xc1,
	0x6e, 0x16, 0x0a, 0x32, 0xe6, 0x24, 0x4c, 0xb9, 0x69, 0xc6, 0xb6, 0x3b, 0xd1, 0x62, 0xdc, 0xde,
	0x0a, 0xb3, 0x0e, 0x72, 0x18, 0x92, 0x4d, 0xa2, 0xcf, 0x04, 0x4a, 0x0c, 0x82, 0x84, 0x12, 0x03,
	0x28, 0xc1, 0x44, 0x9f, 0x16, 0x94, 0x18, 0x44, 0x0c, 0x25, 0x06, 0x20, 0x23, 0xe6, 0xf0, 0xc2,
	0x41, 0x89, 0x90, 0xe6, 0x86, 0xb8, 0xac, 0x01, 0xab, 0x61, 0xd0, 0x0f, 0x88, 0x58, 0xb6, 0x88,
	0x97, 0x68, 0x39, 0x84, 0x25, 0x79, 0x7a, 0xa0, 0x03, 0xa3, 0x7f, 0x82, 0x0c, 0x33, 0x47, 0xbc,
	0xb2, 0x27, 0x23, 0x00, 0x2e, 0x79, 0xf9, 0x50, 0x1b, 0xfe, 0xd2, 0x5b, 0x78, 0xda, 0x81, 0x94,
	0xe8, 0xb7, 0xaf, 0xdb, 0xe5, 0x80, 0xec, 0x79, 0x75, 0x34, 0x7f, 0x82, 0x23, 0x17, 0x59, 0xa2,
	0xbe, 0xfb, 0x00, 0xe3, 0x64, 0xc2, 0x8b, 0x98, 0xf5, 0x1d, 0x7a, 0x1c, 0xc6, 0xc4, 0x59, 0x3d,
	0x1d, 0x61, 0xfe, 0xc9, 0x71, 0xb8, 0xc1, 0x7c, 0x60, 0x87, 0x75, 0xf4, 0x81, 0x3e, 0x12, 0xe9,
	0x03, 0x5d, 0x28, 0xa2, 0xb9, 0x83, 0x3f, 0x32, 0xfb, 0x94, 0x24, 0xb3, 0xcb, 0x49, 0xf1, 0x0e,
	0x9e, 0x75, 0x81, 0x28, 0x9a, 0x3d, 0x74, 0xc9, 0x29, 0x23, 0x5f, 0x68, 0x97, 0xbc, 0x83, 0xc8,
	0xff, 0x4b, 0xee, 0xf3, 0x54, 0xc6, 0x9c, 0x64, 0x52, 0x6c, 0x70, 0x52, 0x0a, 0x4b, 0x59, 0x4a,
	0x61, 0x38, 0x9b, 0x3e, 0xa9, 0xff, 0x1e, 0xbd, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x16, 0xb8,
	0x64, 0xf1, 0x3f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountReply, error)
	UpdateUserAccount(ctx context.Context, in *UpdateUserAccountRequest, opts ...grpc.CallOption) (*UpdateUserAccountReply, error)
	DeleteUserAccount(ctx context.Context, in *DeleteUserAccountRequest, opts ...grpc.CallOption) (*DeleteUserAccountReply, error)
	GetUserAccount(ctx context.Context, in *GetUserAccountRequest, opts ...grpc.CallOption) (*GetUserAccountReply, error)
	CreateTeamsAccount(ctx context.Context, in *CreateTeamsAccountRequest, opts ...grpc.CallOption) (*CreateTeamsAccountReply, error)
	UpdateTeamsAccount(ctx context.Context, in *UpdateTeamsAccountRequest, opts ...grpc.CallOption) (*UpdateTeamsAccountReply, error)
	DeleteTeamsAccount(ctx context.Context, in *DeleteTeamsAccountRequest, opts ...grpc.CallOption) (*DeleteTeamsAccountReply, error)
	GetTeamsAccount(ctx context.Context, in *GetTeamsAccountRequest, opts ...grpc.CallOption) (*GetTeamsAccountReply, error)
	AddUserToTeamsAccount(ctx context.Context, in *AddUserToTeamsAccountRequest, opts ...grpc.CallOption) (*AddUserToTeamsAccountReply, error)
	DeleteUserFromTeamsAccount(ctx context.Context, in *DeleteUserFromTeamsAccountRequest, opts ...grpc.CallOption) (*DeleteUserFromTeamsAccountReply, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error)
	SubscribeToGroup(ctx context.Context, in *SubscribeToGroupRequest, opts ...grpc.CallOption) (*SubscribeToGroupReply, error)
	UnsubscribeFromGroup(ctx context.Context, in *UnsubscribeFromGroupRequest, opts ...grpc.CallOption) (*UnsubscribeFromGroupReply, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupReply, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupReply, error)
	GetGroupByID(ctx context.Context, in *GetGroupByIDRequest, opts ...grpc.CallOption) (*GetGroupByIDReply, error)
	GetGroupByName(ctx context.Context, in *GetGroupByNameRequest, opts ...grpc.CallOption) (*GetGroupByNameReply, error)
	IsGroupPrivate(ctx context.Context, in *IsGroupPrivateRequest, opts ...grpc.CallOption) (*IsGroupPrivateReply, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountReply, error) {
	out := new(CreateUserAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/CreateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUserAccount(ctx context.Context, in *UpdateUserAccountRequest, opts ...grpc.CallOption) (*UpdateUserAccountReply, error) {
	out := new(UpdateUserAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/UpdateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserAccount(ctx context.Context, in *DeleteUserAccountRequest, opts ...grpc.CallOption) (*DeleteUserAccountReply, error) {
	out := new(DeleteUserAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/DeleteUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserAccount(ctx context.Context, in *GetUserAccountRequest, opts ...grpc.CallOption) (*GetUserAccountReply, error) {
	out := new(GetUserAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateTeamsAccount(ctx context.Context, in *CreateTeamsAccountRequest, opts ...grpc.CallOption) (*CreateTeamsAccountReply, error) {
	out := new(CreateTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/CreateTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateTeamsAccount(ctx context.Context, in *UpdateTeamsAccountRequest, opts ...grpc.CallOption) (*UpdateTeamsAccountReply, error) {
	out := new(UpdateTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/UpdateTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteTeamsAccount(ctx context.Context, in *DeleteTeamsAccountRequest, opts ...grpc.CallOption) (*DeleteTeamsAccountReply, error) {
	out := new(DeleteTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/DeleteTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetTeamsAccount(ctx context.Context, in *GetTeamsAccountRequest, opts ...grpc.CallOption) (*GetTeamsAccountReply, error) {
	out := new(GetTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddUserToTeamsAccount(ctx context.Context, in *AddUserToTeamsAccountRequest, opts ...grpc.CallOption) (*AddUserToTeamsAccountReply, error) {
	out := new(AddUserToTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/AddUserToTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserFromTeamsAccount(ctx context.Context, in *DeleteUserFromTeamsAccountRequest, opts ...grpc.CallOption) (*DeleteUserFromTeamsAccountReply, error) {
	out := new(DeleteUserFromTeamsAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/DeleteUserFromTeamsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error) {
	out := new(CreateGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Users/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SubscribeToGroup(ctx context.Context, in *SubscribeToGroupRequest, opts ...grpc.CallOption) (*SubscribeToGroupReply, error) {
	out := new(SubscribeToGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Users/SubscribeToGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UnsubscribeFromGroup(ctx context.Context, in *UnsubscribeFromGroupRequest, opts ...grpc.CallOption) (*UnsubscribeFromGroupReply, error) {
	out := new(UnsubscribeFromGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Users/UnsubscribeFromGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupReply, error) {
	out := new(DeleteGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Users/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupReply, error) {
	out := new(UpdateGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Users/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetGroupByID(ctx context.Context, in *GetGroupByIDRequest, opts ...grpc.CallOption) (*GetGroupByIDReply, error) {
	out := new(GetGroupByIDReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetGroupByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetGroupByName(ctx context.Context, in *GetGroupByNameRequest, opts ...grpc.CallOption) (*GetGroupByNameReply, error) {
	out := new(GetGroupByNameReply)
	err := c.cc.Invoke(ctx, "/pb.Users/GetGroupByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) IsGroupPrivate(ctx context.Context, in *IsGroupPrivateRequest, opts ...grpc.CallOption) (*IsGroupPrivateReply, error) {
	out := new(IsGroupPrivateReply)
	err := c.cc.Invoke(ctx, "/pb.Users/IsGroupPrivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	CreateUserAccount(context.Context, *CreateUserAccountRequest) (*CreateUserAccountReply, error)
	UpdateUserAccount(context.Context, *UpdateUserAccountRequest) (*UpdateUserAccountReply, error)
	DeleteUserAccount(context.Context, *DeleteUserAccountRequest) (*DeleteUserAccountReply, error)
	GetUserAccount(context.Context, *GetUserAccountRequest) (*GetUserAccountReply, error)
	CreateTeamsAccount(context.Context, *CreateTeamsAccountRequest) (*CreateTeamsAccountReply, error)
	UpdateTeamsAccount(context.Context, *UpdateTeamsAccountRequest) (*UpdateTeamsAccountReply, error)
	DeleteTeamsAccount(context.Context, *DeleteTeamsAccountRequest) (*DeleteTeamsAccountReply, error)
	GetTeamsAccount(context.Context, *GetTeamsAccountRequest) (*GetTeamsAccountReply, error)
	AddUserToTeamsAccount(context.Context, *AddUserToTeamsAccountRequest) (*AddUserToTeamsAccountReply, error)
	DeleteUserFromTeamsAccount(context.Context, *DeleteUserFromTeamsAccountRequest) (*DeleteUserFromTeamsAccountReply, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupReply, error)
	SubscribeToGroup(context.Context, *SubscribeToGroupRequest) (*SubscribeToGroupReply, error)
	UnsubscribeFromGroup(context.Context, *UnsubscribeFromGroupRequest) (*UnsubscribeFromGroupReply, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupReply, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupReply, error)
	GetGroupByID(context.Context, *GetGroupByIDRequest) (*GetGroupByIDReply, error)
	GetGroupByName(context.Context, *GetGroupByNameRequest) (*GetGroupByNameReply, error)
	IsGroupPrivate(context.Context, *IsGroupPrivateRequest) (*IsGroupPrivateReply, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) CreateUserAccount(ctx context.Context, req *CreateUserAccountRequest) (*CreateUserAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAccount not implemented")
}
func (*UnimplementedUsersServer) UpdateUserAccount(ctx context.Context, req *UpdateUserAccountRequest) (*UpdateUserAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAccount not implemented")
}
func (*UnimplementedUsersServer) DeleteUserAccount(ctx context.Context, req *DeleteUserAccountRequest) (*DeleteUserAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAccount not implemented")
}
func (*UnimplementedUsersServer) GetUserAccount(ctx context.Context, req *GetUserAccountRequest) (*GetUserAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAccount not implemented")
}
func (*UnimplementedUsersServer) CreateTeamsAccount(ctx context.Context, req *CreateTeamsAccountRequest) (*CreateTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) UpdateTeamsAccount(ctx context.Context, req *UpdateTeamsAccountRequest) (*UpdateTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) DeleteTeamsAccount(ctx context.Context, req *DeleteTeamsAccountRequest) (*DeleteTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) GetTeamsAccount(ctx context.Context, req *GetTeamsAccountRequest) (*GetTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) AddUserToTeamsAccount(ctx context.Context, req *AddUserToTeamsAccountRequest) (*AddUserToTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserToTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) DeleteUserFromTeamsAccount(ctx context.Context, req *DeleteUserFromTeamsAccountRequest) (*DeleteUserFromTeamsAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserFromTeamsAccount not implemented")
}
func (*UnimplementedUsersServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*CreateGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedUsersServer) SubscribeToGroup(ctx context.Context, req *SubscribeToGroupRequest) (*SubscribeToGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeToGroup not implemented")
}
func (*UnimplementedUsersServer) UnsubscribeFromGroup(ctx context.Context, req *UnsubscribeFromGroupRequest) (*UnsubscribeFromGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubscribeFromGroup not implemented")
}
func (*UnimplementedUsersServer) DeleteGroup(ctx context.Context, req *DeleteGroupRequest) (*DeleteGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (*UnimplementedUsersServer) UpdateGroup(ctx context.Context, req *UpdateGroupRequest) (*UpdateGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedUsersServer) GetGroupByID(ctx context.Context, req *GetGroupByIDRequest) (*GetGroupByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupByID not implemented")
}
func (*UnimplementedUsersServer) GetGroupByName(ctx context.Context, req *GetGroupByNameRequest) (*GetGroupByNameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupByName not implemented")
}
func (*UnimplementedUsersServer) IsGroupPrivate(ctx context.Context, req *IsGroupPrivateRequest) (*IsGroupPrivateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsGroupPrivate not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUserAccount(ctx, req.(*CreateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/UpdateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUserAccount(ctx, req.(*UpdateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/DeleteUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserAccount(ctx, req.(*DeleteUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserAccount(ctx, req.(*GetUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/CreateTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateTeamsAccount(ctx, req.(*CreateTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/UpdateTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateTeamsAccount(ctx, req.(*UpdateTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/DeleteTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteTeamsAccount(ctx, req.(*DeleteTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetTeamsAccount(ctx, req.(*GetTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddUserToTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddUserToTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/AddUserToTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddUserToTeamsAccount(ctx, req.(*AddUserToTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserFromTeamsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserFromTeamsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserFromTeamsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/DeleteUserFromTeamsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserFromTeamsAccount(ctx, req.(*DeleteUserFromTeamsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SubscribeToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SubscribeToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/SubscribeToGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SubscribeToGroup(ctx, req.(*SubscribeToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UnsubscribeFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UnsubscribeFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/UnsubscribeFromGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UnsubscribeFromGroup(ctx, req.(*UnsubscribeFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetGroupByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetGroupByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetGroupByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetGroupByID(ctx, req.(*GetGroupByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetGroupByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetGroupByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/GetGroupByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetGroupByName(ctx, req.(*GetGroupByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_IsGroupPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsGroupPrivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).IsGroupPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/IsGroupPrivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).IsGroupPrivate(ctx, req.(*IsGroupPrivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserAccount",
			Handler:    _Users_CreateUserAccount_Handler,
		},
		{
			MethodName: "UpdateUserAccount",
			Handler:    _Users_UpdateUserAccount_Handler,
		},
		{
			MethodName: "DeleteUserAccount",
			Handler:    _Users_DeleteUserAccount_Handler,
		},
		{
			MethodName: "GetUserAccount",
			Handler:    _Users_GetUserAccount_Handler,
		},
		{
			MethodName: "CreateTeamsAccount",
			Handler:    _Users_CreateTeamsAccount_Handler,
		},
		{
			MethodName: "UpdateTeamsAccount",
			Handler:    _Users_UpdateTeamsAccount_Handler,
		},
		{
			MethodName: "DeleteTeamsAccount",
			Handler:    _Users_DeleteTeamsAccount_Handler,
		},
		{
			MethodName: "GetTeamsAccount",
			Handler:    _Users_GetTeamsAccount_Handler,
		},
		{
			MethodName: "AddUserToTeamsAccount",
			Handler:    _Users_AddUserToTeamsAccount_Handler,
		},
		{
			MethodName: "DeleteUserFromTeamsAccount",
			Handler:    _Users_DeleteUserFromTeamsAccount_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Users_CreateGroup_Handler,
		},
		{
			MethodName: "SubscribeToGroup",
			Handler:    _Users_SubscribeToGroup_Handler,
		},
		{
			MethodName: "UnsubscribeFromGroup",
			Handler:    _Users_UnsubscribeFromGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Users_DeleteGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Users_UpdateGroup_Handler,
		},
		{
			MethodName: "GetGroupByID",
			Handler:    _Users_GetGroupByID_Handler,
		},
		{
			MethodName: "GetGroupByName",
			Handler:    _Users_GetGroupByName_Handler,
		},
		{
			MethodName: "IsGroupPrivate",
			Handler:    _Users_IsGroupPrivate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/pkg/grpc/pb/users.proto",
}
