// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendEmailReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailReply) Reset()         { *m = SendEmailReply{} }
func (m *SendEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailReply) ProtoMessage()    {}
func (*SendEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *SendEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReply.Unmarshal(m, b)
}
func (m *SendEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReply.Merge(m, src)
}
func (m *SendEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailReply.Size(m)
}
func (m *SendEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReply proto.InternalMessageInfo

func (m *SendEmailReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SendWelcomeToLensEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeToLensEmailRequest) Reset()         { *m = SendWelcomeToLensEmailRequest{} }
func (m *SendWelcomeToLensEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeToLensEmailRequest) ProtoMessage()    {}
func (*SendWelcomeToLensEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *SendWelcomeToLensEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Unmarshal(m, b)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeToLensEmailRequest.Merge(m, src)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Size(m)
}
func (m *SendWelcomeToLensEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeToLensEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeToLensEmailRequest proto.InternalMessageInfo

func (m *SendWelcomeToLensEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SendWelcomeToLensEmailReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeToLensEmailReply) Reset()         { *m = SendWelcomeToLensEmailReply{} }
func (m *SendWelcomeToLensEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeToLensEmailReply) ProtoMessage()    {}
func (*SendWelcomeToLensEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *SendWelcomeToLensEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Unmarshal(m, b)
}
func (m *SendWelcomeToLensEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Marshal(b, m, deterministic)
}
func (m *SendWelcomeToLensEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeToLensEmailReply.Merge(m, src)
}
func (m *SendWelcomeToLensEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Size(m)
}
func (m *SendWelcomeToLensEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeToLensEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeToLensEmailReply proto.InternalMessageInfo

func (m *SendWelcomeToLensEmailReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SendPasswordChangeEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordChangeEmailRequest) Reset()         { *m = SendPasswordChangeEmailRequest{} }
func (m *SendPasswordChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendPasswordChangeEmailRequest) ProtoMessage()    {}
func (*SendPasswordChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4}
}

func (m *SendPasswordChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Unmarshal(m, b)
}
func (m *SendPasswordChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendPasswordChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordChangeEmailRequest.Merge(m, src)
}
func (m *SendPasswordChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Size(m)
}
func (m *SendPasswordChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordChangeEmailRequest proto.InternalMessageInfo

func (m *SendPasswordChangeEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SendPasswordChangeEmailReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordChangeEmailReply) Reset()         { *m = SendPasswordChangeEmailReply{} }
func (m *SendPasswordChangeEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendPasswordChangeEmailReply) ProtoMessage()    {}
func (*SendPasswordChangeEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5}
}

func (m *SendPasswordChangeEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Unmarshal(m, b)
}
func (m *SendPasswordChangeEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Marshal(b, m, deterministic)
}
func (m *SendPasswordChangeEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordChangeEmailReply.Merge(m, src)
}
func (m *SendPasswordChangeEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Size(m)
}
func (m *SendPasswordChangeEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordChangeEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordChangeEmailReply proto.InternalMessageInfo

func (m *SendPasswordChangeEmailReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SendEmailAccountResetEmailRequest struct {
	OldEmail             string   `protobuf:"bytes,1,opt,name=oldEmail,proto3" json:"oldEmail,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=newEmail,proto3" json:"newEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailAccountResetEmailRequest) Reset()         { *m = SendEmailAccountResetEmailRequest{} }
func (m *SendEmailAccountResetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailAccountResetEmailRequest) ProtoMessage()    {}
func (*SendEmailAccountResetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6}
}

func (m *SendEmailAccountResetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailAccountResetEmailRequest.Merge(m, src)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Size(m)
}
func (m *SendEmailAccountResetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailAccountResetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailAccountResetEmailRequest proto.InternalMessageInfo

func (m *SendEmailAccountResetEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *SendEmailAccountResetEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type SendEmailAccountResetEmailReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailAccountResetEmailReply) Reset()         { *m = SendEmailAccountResetEmailReply{} }
func (m *SendEmailAccountResetEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailAccountResetEmailReply) ProtoMessage()    {}
func (*SendEmailAccountResetEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{7}
}

func (m *SendEmailAccountResetEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Unmarshal(m, b)
}
func (m *SendEmailAccountResetEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailAccountResetEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailAccountResetEmailReply.Merge(m, src)
}
func (m *SendEmailAccountResetEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Size(m)
}
func (m *SendEmailAccountResetEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailAccountResetEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailAccountResetEmailReply proto.InternalMessageInfo

func (m *SendEmailAccountResetEmailReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "pb.SendEmailRequest")
	proto.RegisterType((*SendEmailReply)(nil), "pb.SendEmailReply")
	proto.RegisterType((*SendWelcomeToLensEmailRequest)(nil), "pb.SendWelcomeToLensEmailRequest")
	proto.RegisterType((*SendWelcomeToLensEmailReply)(nil), "pb.SendWelcomeToLensEmailReply")
	proto.RegisterType((*SendPasswordChangeEmailRequest)(nil), "pb.SendPasswordChangeEmailRequest")
	proto.RegisterType((*SendPasswordChangeEmailReply)(nil), "pb.SendPasswordChangeEmailReply")
	proto.RegisterType((*SendEmailAccountResetEmailRequest)(nil), "pb.SendEmailAccountResetEmailRequest")
	proto.RegisterType((*SendEmailAccountResetEmailReply)(nil), "pb.SendEmailAccountResetEmailReply")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07) }

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x4b, 0xf3, 0x30,
	0x18, 0x65, 0x85, 0xf7, 0xd5, 0x3d, 0xc8, 0x90, 0x87, 0xa1, 0x25, 0x7e, 0xac, 0x8b, 0x08, 0xde,
	0x58, 0x50, 0x99, 0xf7, 0x2a, 0xde, 0x89, 0x48, 0x15, 0xbc, 0x50, 0x90, 0x7e, 0x3c, 0xba, 0x40,
	0x97, 0xd4, 0x35, 0x63, 0xec, 0x4f, 0xfb, 0x1b, 0x24, 0xeb, 0x5a, 0xb6, 0xd1, 0x74, 0x5e, 0x9e,
	0xe4, 0x7c, 0x34, 0xe7, 0x50, 0x40, 0xa9, 0xb4, 0xf8, 0x14, 0x71, 0xa8, 0x85, 0x92, 0x7e, 0x36,
	0x56, 0x5a, 0xa1, 0x93, 0x45, 0xfc, 0x16, 0x76, 0x9f, 0x49, 0x26, 0xf7, 0xa3, 0x50, 0xa4, 0x01,
	0x7d, 0x4f, 0x28, 0xd7, 0xd8, 0x85, 0x7f, 0x64, 0xb0, 0xdb, 0xf2, 0x5a, 0x67, 0xed, 0xa0, 0x00,
	0xe8, 0xc2, 0x56, 0xac, 0xa4, 0x26, 0xa9, 0x5d, 0x67, 0x7e, 0x5e, 0x42, 0xee, 0x41, 0x67, 0xc9,
	0x23, 0x4b, 0x67, 0xd8, 0x01, 0x47, 0x24, 0x0b, 0xb9, 0x23, 0x12, 0x3e, 0x80, 0x23, 0xc3, 0x78,
	0xa5, 0x34, 0x56, 0x23, 0x7a, 0x51, 0x0f, 0x24, 0xf3, 0xcd, 0x91, 0xfc, 0x1c, 0x0e, 0x6c, 0xb2,
	0xba, 0x94, 0x6b, 0x38, 0x36, 0xf4, 0xa7, 0x30, 0xcf, 0xa7, 0x6a, 0x9c, 0xdc, 0x0d, 0x43, 0xf9,
	0x45, 0x7f, 0x88, 0xf1, 0xe1, 0xd0, 0xaa, 0xab, 0xcb, 0x79, 0x83, 0x7e, 0xf5, 0xde, 0x9b, 0x38,
	0x56, 0x13, 0xa9, 0x03, 0xca, 0x49, 0xaf, 0x44, 0x31, 0xd8, 0x56, 0x69, 0xc1, 0x59, 0x48, 0x2b,
	0x6c, 0xee, 0x24, 0x4d, 0x8b, 0xbb, 0xa2, 0xcb, 0x0a, 0xf3, 0x0b, 0xe8, 0x35, 0x99, 0xd7, 0x7c,
	0xcf, 0xe5, 0x8f, 0x03, 0x3b, 0x8f, 0x4b, 0xf3, 0xe2, 0x00, 0xda, 0x95, 0x07, 0x76, 0xfd, 0x2c,
	0xf2, 0xd7, 0x37, 0x66, 0xb8, 0x76, 0x6a, 0x7c, 0xdf, 0x61, 0xaf, 0xbe, 0x6e, 0xec, 0x97, 0x6c,
	0xeb, 0x82, 0xac, 0xd7, 0x44, 0x31, 0xee, 0x1f, 0xb0, 0x6f, 0x69, 0x19, 0x79, 0xa9, 0xb5, 0x4f,
	0xc7, 0xbc, 0x46, 0x8e, 0x09, 0x18, 0x02, 0xb3, 0x37, 0x87, 0xa7, 0x2b, 0x0f, 0xb6, 0xcd, 0xc6,
	0x4e, 0x36, 0xd1, 0xb2, 0x74, 0x16, 0xfd, 0x9f, 0xff, 0x3f, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0xd9, 0x66, 0x54, 0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error)
	SendWelcomeToLensEmail(ctx context.Context, in *SendWelcomeToLensEmailRequest, opts ...grpc.CallOption) (*SendWelcomeToLensEmailReply, error)
	SendPasswordChangeEmail(ctx context.Context, in *SendPasswordChangeEmailRequest, opts ...grpc.CallOption) (*SendPasswordChangeEmailReply, error)
	SendEmailAccountResetEmail(ctx context.Context, in *SendEmailAccountResetEmailRequest, opts ...grpc.CallOption) (*SendEmailAccountResetEmailReply, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error) {
	out := new(SendEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) SendWelcomeToLensEmail(ctx context.Context, in *SendWelcomeToLensEmailRequest, opts ...grpc.CallOption) (*SendWelcomeToLensEmailReply, error) {
	out := new(SendWelcomeToLensEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/SendWelcomeToLensEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) SendPasswordChangeEmail(ctx context.Context, in *SendPasswordChangeEmailRequest, opts ...grpc.CallOption) (*SendPasswordChangeEmailReply, error) {
	out := new(SendPasswordChangeEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/SendPasswordChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) SendEmailAccountResetEmail(ctx context.Context, in *SendEmailAccountResetEmailRequest, opts ...grpc.CallOption) (*SendEmailAccountResetEmailReply, error) {
	out := new(SendEmailAccountResetEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/SendEmailAccountResetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailReply, error)
	SendWelcomeToLensEmail(context.Context, *SendWelcomeToLensEmailRequest) (*SendWelcomeToLensEmailReply, error)
	SendPasswordChangeEmail(context.Context, *SendPasswordChangeEmailRequest) (*SendPasswordChangeEmailReply, error)
	SendEmailAccountResetEmail(context.Context, *SendEmailAccountResetEmailRequest) (*SendEmailAccountResetEmailReply, error)
}

// UnimplementedNotificationServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (*UnimplementedNotificationServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedNotificationServer) SendWelcomeToLensEmail(ctx context.Context, req *SendWelcomeToLensEmailRequest) (*SendWelcomeToLensEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWelcomeToLensEmail not implemented")
}
func (*UnimplementedNotificationServer) SendPasswordChangeEmail(ctx context.Context, req *SendPasswordChangeEmailRequest) (*SendPasswordChangeEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPasswordChangeEmail not implemented")
}
func (*UnimplementedNotificationServer) SendEmailAccountResetEmail(ctx context.Context, req *SendEmailAccountResetEmailRequest) (*SendEmailAccountResetEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailAccountResetEmail not implemented")
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_SendWelcomeToLensEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWelcomeToLensEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendWelcomeToLensEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/SendWelcomeToLensEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendWelcomeToLensEmail(ctx, req.(*SendWelcomeToLensEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_SendPasswordChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPasswordChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendPasswordChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/SendPasswordChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendPasswordChangeEmail(ctx, req.(*SendPasswordChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_SendEmailAccountResetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailAccountResetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendEmailAccountResetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/SendEmailAccountResetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendEmailAccountResetEmail(ctx, req.(*SendEmailAccountResetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Notification_SendEmail_Handler,
		},
		{
			MethodName: "SendWelcomeToLensEmail",
			Handler:    _Notification_SendWelcomeToLensEmail_Handler,
		},
		{
			MethodName: "SendPasswordChangeEmail",
			Handler:    _Notification_SendPasswordChangeEmail_Handler,
		},
		{
			MethodName: "SendEmailAccountResetEmail",
			Handler:    _Notification_SendEmailAccountResetEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
