// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/common.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Address) Validate() error {
	return nil
}
func (this *Education) Validate() error {
	return nil
}
func (this *Interests) Validate() error {
	for _, item := range this.Topics {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Topics", err)
			}
		}
	}
	for _, item := range this.Industry {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Industry", err)
			}
		}
	}
	return nil
}
func (this *Topic) Validate() error {
	return nil
}
func (this *Industry) Validate() error {
	return nil
}
func (this *Subscriptions) Validate() error {
	return nil
}
func (this *SkillSet) Validate() error {
	for _, item := range this.Skills {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Skills", err)
			}
		}
	}
	return nil
}
func (this *Skill) Validate() error {
	return nil
}
func (this *Contact) Validate() error {
	return nil
}
func (this *SocialMedia) Validate() error {
	return nil
}
func (this *Details) Validate() error {
	return nil
}
func (this *Experience) Validate() error {
	return nil
}
func (this *Investment) Validate() error {
	return nil
}
func (this *Settings) Validate() error {
	if this.Notifications != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Notifications); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Notifications", err)
		}
	}
	if this.Privacy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Privacy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Privacy", err)
		}
	}
	if this.Payment != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Payment); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Payment", err)
		}
	}
	for _, item := range this.Activity {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Activity", err)
			}
		}
	}
	return nil
}
func (this *LoginActivity) Validate() error {
	if this.Location != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Location); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Location", err)
		}
	}
	return nil
}
func (this *Payments) Validate() error {
	if this.Debit != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Debit); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Debit", err)
		}
	}
	if this.Credit != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Credit); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Credit", err)
		}
	}
	if this.SecurityPin != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SecurityPin); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SecurityPin", err)
		}
	}
	return nil
}
func (this *Card) Validate() error {
	return nil
}
func (this *Pin) Validate() error {
	return nil
}
func (this *Privacy) Validate() error {
	return nil
}
func (this *Notification) Validate() error {
	if this.PostsAndComments != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PostsAndComments); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PostsAndComments", err)
		}
	}
	if this.FollowingAndFollowers != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FollowingAndFollowers); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FollowingAndFollowers", err)
		}
	}
	if this.DirectMessages != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DirectMessages); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DirectMessages", err)
		}
	}
	if this.EmailAndSms != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EmailAndSms); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EmailAndSms", err)
		}
	}
	return nil
}
func (this *PostAndCommentsPushNotificationSettings) Validate() error {
	if this.Likes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Likes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Likes", err)
		}
	}
	if this.LikesAndCommentsOnPostsOfYou != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LikesAndCommentsOnPostsOfYou); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LikesAndCommentsOnPostsOfYou", err)
		}
	}
	if this.PostsOfYou != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PostsOfYou); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PostsOfYou", err)
		}
	}
	if this.Comments != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Comments); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Comments", err)
		}
	}
	if this.CommentLikes != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommentLikes); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommentLikes", err)
		}
	}
	return nil
}
func (this *FollowingAndFollowersPushNotificationSettings) Validate() error {
	if this.FollowerRequests != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FollowerRequests); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FollowerRequests", err)
		}
	}
	if this.AcceptedFollowerRequests != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AcceptedFollowerRequests); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AcceptedFollowerRequests", err)
		}
	}
	if this.MentionsInBio != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MentionsInBio); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MentionsInBio", err)
		}
	}
	return nil
}
func (this *DirectMessagesPushNotificationSettings) Validate() error {
	if this.MessageRequests != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MessageRequests); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MessageRequests", err)
		}
	}
	if this.Message != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Message); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Message", err)
		}
	}
	if this.GroupRequests != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.GroupRequests); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("GroupRequests", err)
		}
	}
	return nil
}
func (this *EmailAndSmsPushNotificationSettings) Validate() error {
	if this.FeedbackEmail != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FeedbackEmail); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FeedbackEmail", err)
		}
	}
	if this.ReminderEmails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ReminderEmails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ReminderEmails", err)
		}
	}
	if this.ProductEmails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ProductEmails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ProductEmails", err)
		}
	}
	if this.NewsEmails != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.NewsEmails); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("NewsEmails", err)
		}
	}
	return nil
}
func (this *TieredPushNotificationSetting) Validate() error {
	return nil
}
func (this *PushNotificationSetting) Validate() error {
	return nil
}
