// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications/pkg/grpc/pb/notifications.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

type SendEmailReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailReply) Reset()         { *m = SendEmailReply{} }
func (m *SendEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailReply) ProtoMessage()    {}
func (*SendEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{1}
}

func (m *SendEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReply.Unmarshal(m, b)
}
func (m *SendEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReply.Merge(m, src)
}
func (m *SendEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailReply.Size(m)
}
func (m *SendEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReply proto.InternalMessageInfo

type SendWelcomeToLensEmailRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeToLensEmailRequest) Reset()         { *m = SendWelcomeToLensEmailRequest{} }
func (m *SendWelcomeToLensEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeToLensEmailRequest) ProtoMessage()    {}
func (*SendWelcomeToLensEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{2}
}

func (m *SendWelcomeToLensEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Unmarshal(m, b)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeToLensEmailRequest.Merge(m, src)
}
func (m *SendWelcomeToLensEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeToLensEmailRequest.Size(m)
}
func (m *SendWelcomeToLensEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeToLensEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeToLensEmailRequest proto.InternalMessageInfo

type SendWelcomeToLensEmailReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWelcomeToLensEmailReply) Reset()         { *m = SendWelcomeToLensEmailReply{} }
func (m *SendWelcomeToLensEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendWelcomeToLensEmailReply) ProtoMessage()    {}
func (*SendWelcomeToLensEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{3}
}

func (m *SendWelcomeToLensEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Unmarshal(m, b)
}
func (m *SendWelcomeToLensEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Marshal(b, m, deterministic)
}
func (m *SendWelcomeToLensEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWelcomeToLensEmailReply.Merge(m, src)
}
func (m *SendWelcomeToLensEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendWelcomeToLensEmailReply.Size(m)
}
func (m *SendWelcomeToLensEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWelcomeToLensEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendWelcomeToLensEmailReply proto.InternalMessageInfo

type SendPasswordChangeEmailRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordChangeEmailRequest) Reset()         { *m = SendPasswordChangeEmailRequest{} }
func (m *SendPasswordChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendPasswordChangeEmailRequest) ProtoMessage()    {}
func (*SendPasswordChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{4}
}

func (m *SendPasswordChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Unmarshal(m, b)
}
func (m *SendPasswordChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendPasswordChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordChangeEmailRequest.Merge(m, src)
}
func (m *SendPasswordChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendPasswordChangeEmailRequest.Size(m)
}
func (m *SendPasswordChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordChangeEmailRequest proto.InternalMessageInfo

type SendPasswordChangeEmailReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordChangeEmailReply) Reset()         { *m = SendPasswordChangeEmailReply{} }
func (m *SendPasswordChangeEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendPasswordChangeEmailReply) ProtoMessage()    {}
func (*SendPasswordChangeEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{5}
}

func (m *SendPasswordChangeEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Unmarshal(m, b)
}
func (m *SendPasswordChangeEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Marshal(b, m, deterministic)
}
func (m *SendPasswordChangeEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordChangeEmailReply.Merge(m, src)
}
func (m *SendPasswordChangeEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendPasswordChangeEmailReply.Size(m)
}
func (m *SendPasswordChangeEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordChangeEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordChangeEmailReply proto.InternalMessageInfo

type SendEmailAccountResetEmailRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailAccountResetEmailRequest) Reset()         { *m = SendEmailAccountResetEmailRequest{} }
func (m *SendEmailAccountResetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailAccountResetEmailRequest) ProtoMessage()    {}
func (*SendEmailAccountResetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{6}
}

func (m *SendEmailAccountResetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailAccountResetEmailRequest.Merge(m, src)
}
func (m *SendEmailAccountResetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailAccountResetEmailRequest.Size(m)
}
func (m *SendEmailAccountResetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailAccountResetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailAccountResetEmailRequest proto.InternalMessageInfo

type SendEmailAccountResetEmailReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailAccountResetEmailReply) Reset()         { *m = SendEmailAccountResetEmailReply{} }
func (m *SendEmailAccountResetEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailAccountResetEmailReply) ProtoMessage()    {}
func (*SendEmailAccountResetEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b94f4797c7a2698, []int{7}
}

func (m *SendEmailAccountResetEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Unmarshal(m, b)
}
func (m *SendEmailAccountResetEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailAccountResetEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailAccountResetEmailReply.Merge(m, src)
}
func (m *SendEmailAccountResetEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailAccountResetEmailReply.Size(m)
}
func (m *SendEmailAccountResetEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailAccountResetEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailAccountResetEmailReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "pb.SendEmailRequest")
	proto.RegisterType((*SendEmailReply)(nil), "pb.SendEmailReply")
	proto.RegisterType((*SendWelcomeToLensEmailRequest)(nil), "pb.SendWelcomeToLensEmailRequest")
	proto.RegisterType((*SendWelcomeToLensEmailReply)(nil), "pb.SendWelcomeToLensEmailReply")
	proto.RegisterType((*SendPasswordChangeEmailRequest)(nil), "pb.SendPasswordChangeEmailRequest")
	proto.RegisterType((*SendPasswordChangeEmailReply)(nil), "pb.SendPasswordChangeEmailReply")
	proto.RegisterType((*SendEmailAccountResetEmailRequest)(nil), "pb.SendEmailAccountResetEmailRequest")
	proto.RegisterType((*SendEmailAccountResetEmailReply)(nil), "pb.SendEmailAccountResetEmailReply")
}

func init() {
	proto.RegisterFile("notifications/pkg/grpc/pb/notifications.proto", fileDescriptor_1b94f4797c7a2698)
}

var fileDescriptor_1b94f4797c7a2698 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xa1, 0x07, 0xc1, 0x01, 0xa5, 0x0c, 0xa2, 0xb0, 0xda, 0xa6, 0x49, 0xf1, 0x68, 0x02,
	0x8a, 0x0f, 0x20, 0xe2, 0x4d, 0x44, 0xaa, 0xe0, 0x45, 0x90, 0x64, 0x3b, 0xa6, 0xc1, 0xed, 0xee,
	0x98, 0xdd, 0x22, 0x79, 0x6a, 0x5f, 0x41, 0x56, 0x68, 0xe9, 0x16, 0x37, 0x5e, 0x67, 0xbe, 0xff,
	0x4f, 0xe6, 0x63, 0xe1, 0x42, 0x1b, 0xd7, 0xbc, 0x37, 0xb2, 0x74, 0x8d, 0xd1, 0xb6, 0xe0, 0x8f,
	0xba, 0xa8, 0x5b, 0x96, 0x05, 0x57, 0x45, 0xb0, 0xc9, 0xb9, 0x35, 0xce, 0xe0, 0x80, 0xab, 0x0c,
	0x61, 0xf8, 0x44, 0x7a, 0x7e, 0xb7, 0x2c, 0x1b, 0x35, 0xa3, 0xcf, 0x15, 0x59, 0x97, 0x0d, 0xe1,
	0x70, 0x6b, 0xc6, 0xaa, 0xcb, 0x12, 0x18, 0xf9, 0xc9, 0x0b, 0x29, 0x69, 0x96, 0xf4, 0x6c, 0xee,
	0x49, 0xdb, 0x20, 0x32, 0x82, 0xd3, 0x18, 0xe0, 0xf3, 0x13, 0x18, 0xfb, 0xf5, 0x63, 0x69, 0xed,
	0x97, 0x69, 0xe7, 0xb7, 0x8b, 0x52, 0xd7, 0x14, 0x14, 0x8c, 0xe1, 0x2c, 0x4a, 0xf8, 0x86, 0x29,
	0xa4, 0x9b, 0x7f, 0xba, 0x91, 0xd2, 0xac, 0xb4, 0x9b, 0x91, 0x25, 0x17, 0x94, 0xa4, 0x90, 0xf4,
	0x41, 0xac, 0xba, 0xcb, 0xef, 0x01, 0x1c, 0x3c, 0x6c, 0xbb, 0xc0, 0x6b, 0xd8, 0xdf, 0x84, 0xf0,
	0x28, 0xe7, 0x2a, 0xdf, 0x15, 0x22, 0x70, 0x67, 0xca, 0xaa, 0xc3, 0x57, 0x38, 0xfe, 0xfb, 0x62,
	0x4c, 0xd7, 0x74, 0x54, 0x97, 0x48, 0xfa, 0x10, 0xdf, 0xfe, 0x06, 0x27, 0x11, 0x1d, 0x98, 0xad,
	0xb3, 0x71, 0x9b, 0x62, 0xd2, 0xcb, 0xf8, 0x0f, 0x2c, 0x40, 0xc4, 0x55, 0xe1, 0x79, 0x70, 0x70,
	0xcc, 0xb7, 0x98, 0xfe, 0x87, 0xb1, 0xea, 0xaa, 0xbd, 0xdf, 0xc7, 0x76, 0xf5, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xcb, 0x74, 0x7e, 0xdf, 0x9d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationsClient is the client API for Notifications service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationsClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error)
	SendWelcomeToLensEmail(ctx context.Context, in *SendWelcomeToLensEmailRequest, opts ...grpc.CallOption) (*SendWelcomeToLensEmailReply, error)
	SendPasswordChangeEmail(ctx context.Context, in *SendPasswordChangeEmailRequest, opts ...grpc.CallOption) (*SendPasswordChangeEmailReply, error)
	SendEmailAccountResetEmail(ctx context.Context, in *SendEmailAccountResetEmailRequest, opts ...grpc.CallOption) (*SendEmailAccountResetEmailReply, error)
}

type notificationsClient struct {
	cc *grpc.ClientConn
}

func NewNotificationsClient(cc *grpc.ClientConn) NotificationsClient {
	return &notificationsClient{cc}
}

func (c *notificationsClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error) {
	out := new(SendEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notifications/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationsClient) SendWelcomeToLensEmail(ctx context.Context, in *SendWelcomeToLensEmailRequest, opts ...grpc.CallOption) (*SendWelcomeToLensEmailReply, error) {
	out := new(SendWelcomeToLensEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notifications/SendWelcomeToLensEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationsClient) SendPasswordChangeEmail(ctx context.Context, in *SendPasswordChangeEmailRequest, opts ...grpc.CallOption) (*SendPasswordChangeEmailReply, error) {
	out := new(SendPasswordChangeEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notifications/SendPasswordChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationsClient) SendEmailAccountResetEmail(ctx context.Context, in *SendEmailAccountResetEmailRequest, opts ...grpc.CallOption) (*SendEmailAccountResetEmailReply, error) {
	out := new(SendEmailAccountResetEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Notifications/SendEmailAccountResetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationsServer is the server API for Notifications service.
type NotificationsServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailReply, error)
	SendWelcomeToLensEmail(context.Context, *SendWelcomeToLensEmailRequest) (*SendWelcomeToLensEmailReply, error)
	SendPasswordChangeEmail(context.Context, *SendPasswordChangeEmailRequest) (*SendPasswordChangeEmailReply, error)
	SendEmailAccountResetEmail(context.Context, *SendEmailAccountResetEmailRequest) (*SendEmailAccountResetEmailReply, error)
}

// UnimplementedNotificationsServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationsServer struct {
}

func (*UnimplementedNotificationsServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedNotificationsServer) SendWelcomeToLensEmail(ctx context.Context, req *SendWelcomeToLensEmailRequest) (*SendWelcomeToLensEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWelcomeToLensEmail not implemented")
}
func (*UnimplementedNotificationsServer) SendPasswordChangeEmail(ctx context.Context, req *SendPasswordChangeEmailRequest) (*SendPasswordChangeEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPasswordChangeEmail not implemented")
}
func (*UnimplementedNotificationsServer) SendEmailAccountResetEmail(ctx context.Context, req *SendEmailAccountResetEmailRequest) (*SendEmailAccountResetEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailAccountResetEmail not implemented")
}

func RegisterNotificationsServer(s *grpc.Server, srv NotificationsServer) {
	s.RegisterService(&_Notifications_serviceDesc, srv)
}

func _Notifications_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifications/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifications_SendWelcomeToLensEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWelcomeToLensEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).SendWelcomeToLensEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifications/SendWelcomeToLensEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).SendWelcomeToLensEmail(ctx, req.(*SendWelcomeToLensEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifications_SendPasswordChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPasswordChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).SendPasswordChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifications/SendPasswordChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).SendPasswordChangeEmail(ctx, req.(*SendPasswordChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifications_SendEmailAccountResetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailAccountResetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).SendEmailAccountResetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifications/SendEmailAccountResetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).SendEmailAccountResetEmail(ctx, req.(*SendEmailAccountResetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notifications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Notifications",
	HandlerType: (*NotificationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Notifications_SendEmail_Handler,
		},
		{
			MethodName: "SendWelcomeToLensEmail",
			Handler:    _Notifications_SendWelcomeToLensEmail_Handler,
		},
		{
			MethodName: "SendPasswordChangeEmail",
			Handler:    _Notifications_SendPasswordChangeEmail_Handler,
		},
		{
			MethodName: "SendEmailAccountResetEmail",
			Handler:    _Notifications_SendEmailAccountResetEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications/pkg/grpc/pb/notifications.proto",
}
