// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"

	endpoint "LensPlatform/Lens/notifications/pkg/endpoint"
	pb "LensPlatform/Lens/notifications/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sendEmail                  grpc.Handler
	sendWelcomeToLensEmail     grpc.Handler
	sendPasswordChangeEmail    grpc.Handler
	sendEmailAccountResetEmail grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.NotificationsServer {
	return &grpcServer{
		sendEmail:                  makeSendEmailHandler(endpoints, options["SendEmail"]),
		sendEmailAccountResetEmail: makeSendEmailAccountResetEmailHandler(endpoints, options["SendEmailAccountResetEmail"]),
		sendPasswordChangeEmail:    makeSendPasswordChangeEmailHandler(endpoints, options["SendPasswordChangeEmail"]),
		sendWelcomeToLensEmail:     makeSendWelcomeToLensEmailHandler(endpoints, options["SendWelcomeToLensEmail"]),
	}
}
