// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "LensPlatform/Lens/users/pkg/endpoint"
	http1 "LensPlatform/Lens/users/pkg/http"
	service "LensPlatform/Lens/users/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	initGRPCHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"AddUserToTeamsAccount":      {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "AddUserToTeamsAccount", logger))},
		"CreateGroup":                {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateGroup", logger))},
		"CreateTeamsAccount":         {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateTeamsAccount", logger))},
		"CreateUserAccount":          {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateUserAccount", logger))},
		"DeleteGroup":                {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteGroup", logger))},
		"DeleteTeamsAccount":         {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteTeamsAccount", logger))},
		"DeleteUserAccount":          {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteUserAccount", logger))},
		"DeleteUserFromTeamsAccount": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteUserFromTeamsAccount", logger))},
		"GetGroupByID":               {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetGroupByID", logger))},
		"GetGroupByName":             {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetGroupByName", logger))},
		"GetTeamsAccount":            {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetTeamsAccount", logger))},
		"GetUserAccount":             {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetUserAccount", logger))},
		"IsGroupPrivate":             {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "IsGroupPrivate", logger))},
		"SubscribeToGroup":           {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "SubscribeToGroup", logger))},
		"UnsubscribeFromGroup":       {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UnsubscribeFromGroup", logger))},
		"UpdateGroup":                {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateGroup", logger))},
		"UpdateTeamsAccount":         {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateTeamsAccount", logger))},
		"UpdateUserAccount":          {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateUserAccount", logger))},
	}
	return options
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"AddUserToTeamsAccount":      {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "AddUserToTeamsAccount", logger))},
		"CreateGroup":                {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateGroup", logger))},
		"CreateTeamsAccount":         {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateTeamsAccount", logger))},
		"CreateUserAccount":          {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateUserAccount", logger))},
		"DeleteGroup":                {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "DeleteGroup", logger))},
		"DeleteTeamsAccount":         {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "DeleteTeamsAccount", logger))},
		"DeleteUserAccount":          {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "DeleteUserAccount", logger))},
		"DeleteUserFromTeamsAccount": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "DeleteUserFromTeamsAccount", logger))},
		"GetGroupByID":               {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetGroupByID", logger))},
		"GetGroupByName":             {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetGroupByName", logger))},
		"GetTeamsAccount":            {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetTeamsAccount", logger))},
		"GetUserAccount":             {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetUserAccount", logger))},
		"IsGroupPrivate":             {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "IsGroupPrivate", logger))},
		"SubscribeToGroup":           {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "SubscribeToGroup", logger))},
		"UnsubscribeFromGroup":       {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "UnsubscribeFromGroup", logger))},
		"UpdateGroup":                {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "UpdateGroup", logger))},
		"UpdateTeamsAccount":         {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "UpdateTeamsAccount", logger))},
		"UpdateUserAccount":          {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "UpdateUserAccount", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["CreateUserAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateUserAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateUserAccount"))}
	mw["UpdateUserAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateUserAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateUserAccount"))}
	mw["DeleteUserAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteUserAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteUserAccount"))}
	mw["GetUserAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetUserAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "GetUserAccount"))}
	mw["CreateTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateTeamsAccount"))}
	mw["UpdateTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateTeamsAccount"))}
	mw["DeleteTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteTeamsAccount"))}
	mw["GetTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "GetTeamsAccount"))}
	mw["AddUserToTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "AddUserToTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "AddUserToTeamsAccount"))}
	mw["DeleteUserFromTeamsAccount"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteUserFromTeamsAccount")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteUserFromTeamsAccount"))}
	mw["CreateGroup"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateGroup")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateGroup"))}
	mw["SubscribeToGroup"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SubscribeToGroup")), endpoint.InstrumentingMiddleware(duration.With("method", "SubscribeToGroup"))}
	mw["UnsubscribeFromGroup"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UnsubscribeFromGroup")), endpoint.InstrumentingMiddleware(duration.With("method", "UnsubscribeFromGroup"))}
	mw["DeleteGroup"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteGroup")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteGroup"))}
	mw["UpdateGroup"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateGroup")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateGroup"))}
	mw["GetGroupByID"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetGroupByID")), endpoint.InstrumentingMiddleware(duration.With("method", "GetGroupByID"))}
	mw["GetGroupByName"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetGroupByName")), endpoint.InstrumentingMiddleware(duration.With("method", "GetGroupByName"))}
	mw["IsGroupPrivate"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "IsGroupPrivate")), endpoint.InstrumentingMiddleware(duration.With("method", "IsGroupPrivate"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"CreateUserAccount", "UpdateUserAccount", "DeleteUserAccount", "GetUserAccount", "CreateTeamsAccount", "UpdateTeamsAccount", "DeleteTeamsAccount", "GetTeamsAccount", "AddUserToTeamsAccount", "DeleteUserFromTeamsAccount", "CreateGroup", "SubscribeToGroup", "UnsubscribeFromGroup", "DeleteGroup", "UpdateGroup", "GetGroupByID", "GetGroupByName", "IsGroupPrivate"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
