// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/LensPlatform/Lens-Backend/notification/pkg/endpoint"
	service "github.com/LensPlatform/Lens-Backend/notification/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initGRPCHandler(endpoints, g)
	return g
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"SendEmail":                  {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "SendEmail", logger))},
		"SendEmailAccountResetEmail": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "SendEmailAccountResetEmail", logger))},
		"SendPasswordChangeEmail":    {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "SendPasswordChangeEmail", logger))},
		"SendWelcomeToLensEmail":     {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "SendWelcomeToLensEmail", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["SendEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SendEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "SendEmail"))}
	mw["SendWelcomeToLensEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SendWelcomeToLensEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "SendWelcomeToLensEmail"))}
	mw["SendPasswordChangeEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SendPasswordChangeEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "SendPasswordChangeEmail"))}
	mw["SendEmailAccountResetEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "SendEmailAccountResetEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "SendEmailAccountResetEmail"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"SendEmail", "SendWelcomeToLensEmail", "SendPasswordChangeEmail", "SendEmailAccountResetEmail"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
