// Code generated by protoc-gen-go. DO NOT EDIT.
// source: social/pkg/grpc/pb/social.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FollowUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserRequest) Reset()         { *m = FollowUserRequest{} }
func (m *FollowUserRequest) String() string { return proto.CompactTextString(m) }
func (*FollowUserRequest) ProtoMessage()    {}
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{0}
}

func (m *FollowUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserRequest.Unmarshal(m, b)
}
func (m *FollowUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserRequest.Marshal(b, m, deterministic)
}
func (m *FollowUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserRequest.Merge(m, src)
}
func (m *FollowUserRequest) XXX_Size() int {
	return xxx_messageInfo_FollowUserRequest.Size(m)
}
func (m *FollowUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserRequest proto.InternalMessageInfo

type FollowUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserReply) Reset()         { *m = FollowUserReply{} }
func (m *FollowUserReply) String() string { return proto.CompactTextString(m) }
func (*FollowUserReply) ProtoMessage()    {}
func (*FollowUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{1}
}

func (m *FollowUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserReply.Unmarshal(m, b)
}
func (m *FollowUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserReply.Marshal(b, m, deterministic)
}
func (m *FollowUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserReply.Merge(m, src)
}
func (m *FollowUserReply) XXX_Size() int {
	return xxx_messageInfo_FollowUserReply.Size(m)
}
func (m *FollowUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserReply proto.InternalMessageInfo

type UnFollowerUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowerUserRequest) Reset()         { *m = UnFollowerUserRequest{} }
func (m *UnFollowerUserRequest) String() string { return proto.CompactTextString(m) }
func (*UnFollowerUserRequest) ProtoMessage()    {}
func (*UnFollowerUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{2}
}

func (m *UnFollowerUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowerUserRequest.Unmarshal(m, b)
}
func (m *UnFollowerUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowerUserRequest.Marshal(b, m, deterministic)
}
func (m *UnFollowerUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowerUserRequest.Merge(m, src)
}
func (m *UnFollowerUserRequest) XXX_Size() int {
	return xxx_messageInfo_UnFollowerUserRequest.Size(m)
}
func (m *UnFollowerUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowerUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowerUserRequest proto.InternalMessageInfo

type UnFollowerUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowerUserReply) Reset()         { *m = UnFollowerUserReply{} }
func (m *UnFollowerUserReply) String() string { return proto.CompactTextString(m) }
func (*UnFollowerUserReply) ProtoMessage()    {}
func (*UnFollowerUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{3}
}

func (m *UnFollowerUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowerUserReply.Unmarshal(m, b)
}
func (m *UnFollowerUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowerUserReply.Marshal(b, m, deterministic)
}
func (m *UnFollowerUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowerUserReply.Merge(m, src)
}
func (m *UnFollowerUserReply) XXX_Size() int {
	return xxx_messageInfo_UnFollowerUserReply.Size(m)
}
func (m *UnFollowerUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowerUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowerUserReply proto.InternalMessageInfo

type FollowGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowGroupRequest) Reset()         { *m = FollowGroupRequest{} }
func (m *FollowGroupRequest) String() string { return proto.CompactTextString(m) }
func (*FollowGroupRequest) ProtoMessage()    {}
func (*FollowGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{4}
}

func (m *FollowGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowGroupRequest.Unmarshal(m, b)
}
func (m *FollowGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowGroupRequest.Marshal(b, m, deterministic)
}
func (m *FollowGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowGroupRequest.Merge(m, src)
}
func (m *FollowGroupRequest) XXX_Size() int {
	return xxx_messageInfo_FollowGroupRequest.Size(m)
}
func (m *FollowGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowGroupRequest proto.InternalMessageInfo

type FollowGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowGroupReply) Reset()         { *m = FollowGroupReply{} }
func (m *FollowGroupReply) String() string { return proto.CompactTextString(m) }
func (*FollowGroupReply) ProtoMessage()    {}
func (*FollowGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{5}
}

func (m *FollowGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowGroupReply.Unmarshal(m, b)
}
func (m *FollowGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowGroupReply.Marshal(b, m, deterministic)
}
func (m *FollowGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowGroupReply.Merge(m, src)
}
func (m *FollowGroupReply) XXX_Size() int {
	return xxx_messageInfo_FollowGroupReply.Size(m)
}
func (m *FollowGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_FollowGroupReply proto.InternalMessageInfo

type UnFollowGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowGroupRequest) Reset()         { *m = UnFollowGroupRequest{} }
func (m *UnFollowGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UnFollowGroupRequest) ProtoMessage()    {}
func (*UnFollowGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{6}
}

func (m *UnFollowGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowGroupRequest.Unmarshal(m, b)
}
func (m *UnFollowGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowGroupRequest.Marshal(b, m, deterministic)
}
func (m *UnFollowGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowGroupRequest.Merge(m, src)
}
func (m *UnFollowGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UnFollowGroupRequest.Size(m)
}
func (m *UnFollowGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowGroupRequest proto.InternalMessageInfo

type UnFollowGroupReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowGroupReply) Reset()         { *m = UnFollowGroupReply{} }
func (m *UnFollowGroupReply) String() string { return proto.CompactTextString(m) }
func (*UnFollowGroupReply) ProtoMessage()    {}
func (*UnFollowGroupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{7}
}

func (m *UnFollowGroupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowGroupReply.Unmarshal(m, b)
}
func (m *UnFollowGroupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowGroupReply.Marshal(b, m, deterministic)
}
func (m *UnFollowGroupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowGroupReply.Merge(m, src)
}
func (m *UnFollowGroupReply) XXX_Size() int {
	return xxx_messageInfo_UnFollowGroupReply.Size(m)
}
func (m *UnFollowGroupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowGroupReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowGroupReply proto.InternalMessageInfo

type FollowTeamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowTeamRequest) Reset()         { *m = FollowTeamRequest{} }
func (m *FollowTeamRequest) String() string { return proto.CompactTextString(m) }
func (*FollowTeamRequest) ProtoMessage()    {}
func (*FollowTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{8}
}

func (m *FollowTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowTeamRequest.Unmarshal(m, b)
}
func (m *FollowTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowTeamRequest.Marshal(b, m, deterministic)
}
func (m *FollowTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowTeamRequest.Merge(m, src)
}
func (m *FollowTeamRequest) XXX_Size() int {
	return xxx_messageInfo_FollowTeamRequest.Size(m)
}
func (m *FollowTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowTeamRequest proto.InternalMessageInfo

type FollowTeamReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowTeamReply) Reset()         { *m = FollowTeamReply{} }
func (m *FollowTeamReply) String() string { return proto.CompactTextString(m) }
func (*FollowTeamReply) ProtoMessage()    {}
func (*FollowTeamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{9}
}

func (m *FollowTeamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowTeamReply.Unmarshal(m, b)
}
func (m *FollowTeamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowTeamReply.Marshal(b, m, deterministic)
}
func (m *FollowTeamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowTeamReply.Merge(m, src)
}
func (m *FollowTeamReply) XXX_Size() int {
	return xxx_messageInfo_FollowTeamReply.Size(m)
}
func (m *FollowTeamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowTeamReply.DiscardUnknown(m)
}

var xxx_messageInfo_FollowTeamReply proto.InternalMessageInfo

type UnFollowTeamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowTeamRequest) Reset()         { *m = UnFollowTeamRequest{} }
func (m *UnFollowTeamRequest) String() string { return proto.CompactTextString(m) }
func (*UnFollowTeamRequest) ProtoMessage()    {}
func (*UnFollowTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{10}
}

func (m *UnFollowTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowTeamRequest.Unmarshal(m, b)
}
func (m *UnFollowTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowTeamRequest.Marshal(b, m, deterministic)
}
func (m *UnFollowTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowTeamRequest.Merge(m, src)
}
func (m *UnFollowTeamRequest) XXX_Size() int {
	return xxx_messageInfo_UnFollowTeamRequest.Size(m)
}
func (m *UnFollowTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowTeamRequest proto.InternalMessageInfo

type UnFollowTeamReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnFollowTeamReply) Reset()         { *m = UnFollowTeamReply{} }
func (m *UnFollowTeamReply) String() string { return proto.CompactTextString(m) }
func (*UnFollowTeamReply) ProtoMessage()    {}
func (*UnFollowTeamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_495b8edfd704333c, []int{11}
}

func (m *UnFollowTeamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnFollowTeamReply.Unmarshal(m, b)
}
func (m *UnFollowTeamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnFollowTeamReply.Marshal(b, m, deterministic)
}
func (m *UnFollowTeamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnFollowTeamReply.Merge(m, src)
}
func (m *UnFollowTeamReply) XXX_Size() int {
	return xxx_messageInfo_UnFollowTeamReply.Size(m)
}
func (m *UnFollowTeamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnFollowTeamReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnFollowTeamReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FollowUserRequest)(nil), "pb.FollowUserRequest")
	proto.RegisterType((*FollowUserReply)(nil), "pb.FollowUserReply")
	proto.RegisterType((*UnFollowerUserRequest)(nil), "pb.UnFollowerUserRequest")
	proto.RegisterType((*UnFollowerUserReply)(nil), "pb.UnFollowerUserReply")
	proto.RegisterType((*FollowGroupRequest)(nil), "pb.FollowGroupRequest")
	proto.RegisterType((*FollowGroupReply)(nil), "pb.FollowGroupReply")
	proto.RegisterType((*UnFollowGroupRequest)(nil), "pb.UnFollowGroupRequest")
	proto.RegisterType((*UnFollowGroupReply)(nil), "pb.UnFollowGroupReply")
	proto.RegisterType((*FollowTeamRequest)(nil), "pb.FollowTeamRequest")
	proto.RegisterType((*FollowTeamReply)(nil), "pb.FollowTeamReply")
	proto.RegisterType((*UnFollowTeamRequest)(nil), "pb.UnFollowTeamRequest")
	proto.RegisterType((*UnFollowTeamReply)(nil), "pb.UnFollowTeamReply")
}

func init() { proto.RegisterFile("social/pkg/grpc/pb/social.proto", fileDescriptor_495b8edfd704333c) }

var fileDescriptor_495b8edfd704333c = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x4a, 0xf3, 0x50,
	0x10, 0x86, 0xe1, 0xfb, 0xa0, 0x8b, 0xd7, 0xdf, 0x4c, 0x7e, 0xaa, 0xd9, 0x08, 0xb9, 0x80, 0x04,
	0x74, 0x23, 0x08, 0x82, 0x20, 0xba, 0x57, 0x7b, 0x01, 0x4d, 0x39, 0x14, 0xf1, 0xe8, 0x19, 0x4f,
	0x5a, 0x24, 0x5b, 0xaf, 0x5c, 0xa6, 0xa1, 0xe9, 0x9c, 0x24, 0xdb, 0x67, 0xde, 0xcc, 0x99, 0xf7,
	0x21, 0xb8, 0x6a, 0xdc, 0xea, 0x7d, 0x69, 0x2b, 0xfe, 0x58, 0x57, 0x6b, 0xcf, 0xab, 0x8a, 0xeb,
	0xaa, 0x43, 0x25, 0x7b, 0xb7, 0x71, 0xf4, 0x8f, 0xeb, 0x22, 0x46, 0xf4, 0xe4, 0xac, 0x75, 0x3f,
	0x8b, 0xc6, 0xf8, 0x17, 0xf3, 0xbd, 0x35, 0xcd, 0xa6, 0x88, 0x70, 0xa6, 0x21, 0xdb, 0xb6, 0x98,
	0x23, 0x5d, 0x7c, 0x75, 0xd0, 0x78, 0x9d, 0x4d, 0x11, 0x0f, 0x07, 0x92, 0x4f, 0x40, 0x1d, 0x7c,
	0xf6, 0x6e, 0xcb, 0xfb, 0x30, 0xe1, 0x3c, 0xa0, 0x92, 0xcc, 0x90, 0xec, 0x17, 0x04, 0xd9, 0x04,
	0x34, 0xe0, 0x92, 0xee, 0xef, 0x7d, 0x33, 0xcb, 0xcf, 0xd1, 0xbd, 0x1d, 0x94, 0x9c, 0x3a, 0x4b,
	0x27, 0x63, 0x44, 0x21, 0x66, 0xdb, 0x5e, 0xff, 0xfe, 0xc7, 0xec, 0x75, 0x27, 0x86, 0x6e, 0x81,
	0x43, 0x73, 0x4a, 0x4b, 0xae, 0xcb, 0x91, 0x9e, 0x3c, 0x1e, 0x62, 0xb6, 0x2d, 0x3d, 0xe2, 0x34,
	0xf4, 0x40, 0x97, 0x12, 0x9b, 0x94, 0x96, 0xcf, 0xa7, 0x46, 0xb2, 0xe5, 0x0e, 0x47, 0xaa, 0x32,
	0x65, 0x87, 0x97, 0xb4, 0x9b, 0x3c, 0x19, 0x71, 0xf9, 0xf8, 0x01, 0x27, 0x81, 0x31, 0xba, 0xd0,
	0xcf, 0x04, 0x0b, 0xb2, 0x89, 0x89, 0xac, 0xe8, 0xfb, 0x8b, 0x1d, 0xdd, 0x5f, 0x49, 0xd4, 0xfd,
	0x7b, 0x89, 0x74, 0x8f, 0x63, 0x6d, 0x96, 0x82, 0x8a, 0xfa, 0xeb, 0x74, 0x3c, 0x60, 0xdb, 0xd6,
	0xb3, 0xdd, 0x3f, 0x79, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0xab, 0x73, 0x04, 0xfd, 0xb6, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocialClient interface {
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error)
	UnFollowerUser(ctx context.Context, in *UnFollowerUserRequest, opts ...grpc.CallOption) (*UnFollowerUserReply, error)
	FollowGroup(ctx context.Context, in *FollowGroupRequest, opts ...grpc.CallOption) (*FollowGroupReply, error)
	UnFollowGroup(ctx context.Context, in *UnFollowGroupRequest, opts ...grpc.CallOption) (*UnFollowGroupReply, error)
	FollowTeam(ctx context.Context, in *FollowTeamRequest, opts ...grpc.CallOption) (*FollowTeamReply, error)
	UnFollowTeam(ctx context.Context, in *UnFollowTeamRequest, opts ...grpc.CallOption) (*UnFollowTeamReply, error)
}

type socialClient struct {
	cc *grpc.ClientConn
}

func NewSocialClient(cc *grpc.ClientConn) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserReply, error) {
	out := new(FollowUserReply)
	err := c.cc.Invoke(ctx, "/pb.Social/FollowUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UnFollowerUser(ctx context.Context, in *UnFollowerUserRequest, opts ...grpc.CallOption) (*UnFollowerUserReply, error) {
	out := new(UnFollowerUserReply)
	err := c.cc.Invoke(ctx, "/pb.Social/UnFollowerUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FollowGroup(ctx context.Context, in *FollowGroupRequest, opts ...grpc.CallOption) (*FollowGroupReply, error) {
	out := new(FollowGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Social/FollowGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UnFollowGroup(ctx context.Context, in *UnFollowGroupRequest, opts ...grpc.CallOption) (*UnFollowGroupReply, error) {
	out := new(UnFollowGroupReply)
	err := c.cc.Invoke(ctx, "/pb.Social/UnFollowGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FollowTeam(ctx context.Context, in *FollowTeamRequest, opts ...grpc.CallOption) (*FollowTeamReply, error) {
	out := new(FollowTeamReply)
	err := c.cc.Invoke(ctx, "/pb.Social/FollowTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UnFollowTeam(ctx context.Context, in *UnFollowTeamRequest, opts ...grpc.CallOption) (*UnFollowTeamReply, error) {
	out := new(UnFollowTeamReply)
	err := c.cc.Invoke(ctx, "/pb.Social/UnFollowTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
type SocialServer interface {
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserReply, error)
	UnFollowerUser(context.Context, *UnFollowerUserRequest) (*UnFollowerUserReply, error)
	FollowGroup(context.Context, *FollowGroupRequest) (*FollowGroupReply, error)
	UnFollowGroup(context.Context, *UnFollowGroupRequest) (*UnFollowGroupReply, error)
	FollowTeam(context.Context, *FollowTeamRequest) (*FollowTeamReply, error)
	UnFollowTeam(context.Context, *UnFollowTeamRequest) (*UnFollowTeamReply, error)
}

// UnimplementedSocialServer can be embedded to have forward compatible implementations.
type UnimplementedSocialServer struct {
}

func (*UnimplementedSocialServer) FollowUser(ctx context.Context, req *FollowUserRequest) (*FollowUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (*UnimplementedSocialServer) UnFollowerUser(ctx context.Context, req *UnFollowerUserRequest) (*UnFollowerUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnFollowerUser not implemented")
}
func (*UnimplementedSocialServer) FollowGroup(ctx context.Context, req *FollowGroupRequest) (*FollowGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowGroup not implemented")
}
func (*UnimplementedSocialServer) UnFollowGroup(ctx context.Context, req *UnFollowGroupRequest) (*UnFollowGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnFollowGroup not implemented")
}
func (*UnimplementedSocialServer) FollowTeam(ctx context.Context, req *FollowTeamRequest) (*FollowTeamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowTeam not implemented")
}
func (*UnimplementedSocialServer) UnFollowTeam(ctx context.Context, req *UnFollowTeamRequest) (*UnFollowTeamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnFollowTeam not implemented")
}

func RegisterSocialServer(s *grpc.Server, srv SocialServer) {
	s.RegisterService(&_Social_serviceDesc, srv)
}

func _Social_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/FollowUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UnFollowerUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnFollowerUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UnFollowerUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/UnFollowerUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UnFollowerUser(ctx, req.(*UnFollowerUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FollowGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/FollowGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowGroup(ctx, req.(*FollowGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UnFollowGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnFollowGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UnFollowGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/UnFollowGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UnFollowGroup(ctx, req.(*UnFollowGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FollowTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/FollowTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowTeam(ctx, req.(*FollowTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UnFollowTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnFollowTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UnFollowTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Social/UnFollowTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UnFollowTeam(ctx, req.(*UnFollowTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Social_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowUser",
			Handler:    _Social_FollowUser_Handler,
		},
		{
			MethodName: "UnFollowerUser",
			Handler:    _Social_UnFollowerUser_Handler,
		},
		{
			MethodName: "FollowGroup",
			Handler:    _Social_FollowGroup_Handler,
		},
		{
			MethodName: "UnFollowGroup",
			Handler:    _Social_UnFollowGroup_Handler,
		},
		{
			MethodName: "FollowTeam",
			Handler:    _Social_FollowTeam_Handler,
		},
		{
			MethodName: "UnFollowTeam",
			Handler:    _Social_UnFollowTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social/pkg/grpc/pb/social.proto",
}
