basePath: /
host: localhost:8085
info:
  contact:
    name: Yoan Yomba
    url: https://github.com/LensPlatform/Lens
  description: Go microservice for users, teams, and groups logic.
  license:
    name: MIT License
    url: https://github.com/stefanprodan/podinfo/blob/master/LICENSE
  title: Lens Platform Users Microservice
  version: 1.0.0
paths: {}
schemes:
- http
- https
swagger: "2.0"
