// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/LensPlatform/Lens/social/pkg/endpoint"
	pb "github.com/LensPlatform/Lens/social/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	followUser     grpc.Handler
	unFollowerUser grpc.Handler
	followGroup    grpc.Handler
	unFollowGroup  grpc.Handler
	followTeam     grpc.Handler
	unFollowTeam   grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.SocialServer {
	return &grpcServer{
		followGroup:    makeFollowGroupHandler(endpoints, options["FollowGroup"]),
		followTeam:     makeFollowTeamHandler(endpoints, options["FollowTeam"]),
		followUser:     makeFollowUserHandler(endpoints, options["FollowUser"]),
		unFollowGroup:  makeUnFollowGroupHandler(endpoints, options["UnFollowGroup"]),
		unFollowTeam:   makeUnFollowTeamHandler(endpoints, options["UnFollowTeam"]),
		unFollowerUser: makeUnFollowerUserHandler(endpoints, options["UnFollowerUser"]),
	}
}
